# Generated by Django 4.1.2 on 2022-10-11 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radisna', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pension',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
