# Generated by Django 4.1.2 on 2022-10-05 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radisna', '0002_alter_user_date_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default=390871, max_length=24),
            preserve_default=False,
        ),
    ]
