# Generated by Django 4.1.2 on 2022-10-11 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radisna', '0002_user_pension'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='apartment',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='home',
            field=models.PositiveIntegerField(),
        ),
    ]
