# Generated by Django 4.1.2 on 2022-10-05 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radisna', '0003_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=24),
        ),
    ]
