# Generated by Django 4.1.2 on 2022-10-11 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radisna', '0003_alter_user_apartment_alter_user_home'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='home_index',
            field=models.CharField(choices=[('a', 'a'), ('b', 'б')], max_length=1, null=True),
        ),
    ]
