# Generated by Django 4.1.2 on 2022-10-05 14:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radisna', '0004_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_birth',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 5, 14, 30, 49, 535316, tzinfo=datetime.timezone.utc)),
        ),
    ]
