# Generated by Django 4.1.2 on 2022-10-11 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radisna', '0004_user_home_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='home_index',
            field=models.CharField(blank=True, choices=[('a', 'a'), ('b', 'б')], max_length=1, null=True),
        ),
    ]
