# Generated by Django 4.1.2 on 2022-10-11 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radisna', '0006_user_apartment_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='apartment_index',
            field=models.CharField(blank=True, choices=[('а', 'а'), ('б', 'б'), ('в', 'в'), ('г', 'г')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='home_index',
            field=models.CharField(blank=True, choices=[('а', 'а'), ('б', 'б'), ('в', 'в'), ('г', 'г')], max_length=1, null=True),
        ),
    ]
