# Generated by Django 4.1.2 on 2022-10-08 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radisna', '0010_alter_user_date_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='invalid',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='many_children',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
